INSERT INTO config VALUES (1, 'SocketTimesheet :: Php Web Based Timesheet', 'SocketTimesheet :: Php Web Based Timesheet, Exp', '3.0', 'Creative Digital Resources Sdn. Bhd.', 'www.creative-dr.com', '2006-01-14', 'socket_timesheet', 'st_', '/sockettimesheet_new/', 1024000, 0, 1, 3, 10);


INSERT INTO country VALUES ('AF', 'Afghanistan');
INSERT INTO country VALUES ('AL', 'Albania');
INSERT INTO country VALUES ('DZ', 'Algeria');
INSERT INTO country VALUES ('AS', 'American Samoa');
INSERT INTO country VALUES ('AD', 'Andorra');
INSERT INTO country VALUES ('AO', 'Angola');
INSERT INTO country VALUES ('AI', 'Anguilla');
INSERT INTO country VALUES ('AQ', 'Antarctica');
INSERT INTO country VALUES ('AG', 'Antigua And Barbuda');
INSERT INTO country VALUES ('AR', 'Argentina');
INSERT INTO country VALUES ('AM', 'Armenia');
INSERT INTO country VALUES ('AW', 'Aruba');
INSERT INTO country VALUES ('AU', 'Australia');
INSERT INTO country VALUES ('AT', 'Austria');
INSERT INTO country VALUES ('AZ', 'Azerbaijan');
INSERT INTO country VALUES ('BS', 'Bahamas, The');
INSERT INTO country VALUES ('BH', 'Bahrain');
INSERT INTO country VALUES ('BD', 'Bangladesh');
INSERT INTO country VALUES ('BB', 'Barbados');
INSERT INTO country VALUES ('BY', 'Belarus');
INSERT INTO country VALUES ('BE', 'Belgium');
INSERT INTO country VALUES ('BZ', 'Belize');
INSERT INTO country VALUES ('BJ', 'Benin');
INSERT INTO country VALUES ('BM', 'Bermuda');
INSERT INTO country VALUES ('BT', 'Bhutan');
INSERT INTO country VALUES ('BO', 'Bolivia');
INSERT INTO country VALUES ('BA', 'Bosnia and Herzegovina');
INSERT INTO country VALUES ('BW', 'Botswana');
INSERT INTO country VALUES ('BV', 'Bouvet Island');
INSERT INTO country VALUES ('BR', 'Brazil');
INSERT INTO country VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO country VALUES ('BN', 'Brunei');
INSERT INTO country VALUES ('BG', 'Bulgaria');
INSERT INTO country VALUES ('BF', 'Burkina Faso');
INSERT INTO country VALUES ('BI', 'Burundi');
INSERT INTO country VALUES ('KH', 'Cambodia');
INSERT INTO country VALUES ('CM', 'Cameroon');
INSERT INTO country VALUES ('CA', 'Canada');
INSERT INTO country VALUES ('CV', 'Cape Verde');
INSERT INTO country VALUES ('KY', 'Cayman Islands');
INSERT INTO country VALUES ('CF', 'Central African Republic');
INSERT INTO country VALUES ('TD', 'Chad');
INSERT INTO country VALUES ('CL', 'Chile');
INSERT INTO country VALUES ('CN', 'China');
INSERT INTO country VALUES ('CX', 'Christmas Island');
INSERT INTO country VALUES ('CC', 'Cocos (Keeling) Islands');
INSERT INTO country VALUES ('CO', 'Colombia');
INSERT INTO country VALUES ('KM', 'Comoros');
INSERT INTO country VALUES ('CG', 'Congo');
INSERT INTO country VALUES ('CD', 'Congo, Democractic Republic of the');
INSERT INTO country VALUES ('CK', 'Cook Islands');
INSERT INTO country VALUES ('CR', 'Costa Rica');
INSERT INTO country VALUES ('CI', 'Cote D''Ivoire (Ivory Coast)');
INSERT INTO country VALUES ('HR', 'Croatia (Hrvatska)');
INSERT INTO country VALUES ('CU', 'Cuba');
INSERT INTO country VALUES ('CY', 'Cyprus');
INSERT INTO country VALUES ('CZ', 'Czech Republic');
INSERT INTO country VALUES ('DK', 'Denmark');
INSERT INTO country VALUES ('DJ', 'Djibouti');
INSERT INTO country VALUES ('DM', 'Dominica');
INSERT INTO country VALUES ('DO', 'Dominican Republic');
INSERT INTO country VALUES ('TP', 'East Timor');
INSERT INTO country VALUES ('EC', 'Ecuador');
INSERT INTO country VALUES ('EG', 'Egypt');
INSERT INTO country VALUES ('SV', 'El Salvador');
INSERT INTO country VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO country VALUES ('ER', 'Eritrea');
INSERT INTO country VALUES ('EE', 'Estonia');
INSERT INTO country VALUES ('ET', 'Ethiopia');
INSERT INTO country VALUES ('FK', 'Falkland Islands (Islas Malvinas)');
INSERT INTO country VALUES ('FO', 'Faroe Islands');
INSERT INTO country VALUES ('FJ', 'Fiji Islands');
INSERT INTO country VALUES ('FI', 'Finland');
INSERT INTO country VALUES ('FR', 'France');
INSERT INTO country VALUES ('GF', 'French Guiana');
INSERT INTO country VALUES ('PF', 'French Polynesia');
INSERT INTO country VALUES ('TF', 'French Southern Territories');
INSERT INTO country VALUES ('GA', 'Gabon');
INSERT INTO country VALUES ('GM', 'Gambia, The');
INSERT INTO country VALUES ('GE', 'Georgia');
INSERT INTO country VALUES ('DE', 'Germany');
INSERT INTO country VALUES ('GH', 'Ghana');
INSERT INTO country VALUES ('GI', 'Gibraltar');
INSERT INTO country VALUES ('GR', 'Greece');
INSERT INTO country VALUES ('GL', 'Greenland');
INSERT INTO country VALUES ('GD', 'Grenada');
INSERT INTO country VALUES ('GP', 'Guadeloupe');
INSERT INTO country VALUES ('GU', 'Guam');
INSERT INTO country VALUES ('GT', 'Guatemala');
INSERT INTO country VALUES ('GN', 'Guinea');
INSERT INTO country VALUES ('GW', 'Guinea-Bissau');
INSERT INTO country VALUES ('GY', 'Guyana');
INSERT INTO country VALUES ('HT', 'Haiti');
INSERT INTO country VALUES ('HM', 'Heard and McDonald Islands');
INSERT INTO country VALUES ('HN', 'Honduras');
INSERT INTO country VALUES ('HK', 'Hong Kong S.A.R.');
INSERT INTO country VALUES ('HU', 'Hungary');
INSERT INTO country VALUES ('IS', 'Iceland');
INSERT INTO country VALUES ('IN', 'India');
INSERT INTO country VALUES ('ID', 'Indonesia');
INSERT INTO country VALUES ('IR', 'Iran');
INSERT INTO country VALUES ('IQ', 'Iraq');
INSERT INTO country VALUES ('IE', 'Ireland');
INSERT INTO country VALUES ('IL', 'Israel');
INSERT INTO country VALUES ('IT', 'Italy');
INSERT INTO country VALUES ('JM', 'Jamaica');
INSERT INTO country VALUES ('JP', 'Japan');
INSERT INTO country VALUES ('JO', 'Jordan');
INSERT INTO country VALUES ('KZ', 'Kazakhstan');
INSERT INTO country VALUES ('KE', 'Kenya');
INSERT INTO country VALUES ('KI', 'Kiribati');
INSERT INTO country VALUES ('KR', 'Korea');
INSERT INTO country VALUES ('KP', 'Korea, North');
INSERT INTO country VALUES ('KW', 'Kuwait');
INSERT INTO country VALUES ('KG', 'Kyrgyzstan');
INSERT INTO country VALUES ('LA', 'Laos');
INSERT INTO country VALUES ('LV', 'Latvia');
INSERT INTO country VALUES ('LB', 'Lebanon');
INSERT INTO country VALUES ('LS', 'Lesotho');
INSERT INTO country VALUES ('LR', 'Liberia');
INSERT INTO country VALUES ('LY', 'Libya');
INSERT INTO country VALUES ('LI', 'Liechtenstein');
INSERT INTO country VALUES ('LT', 'Lithuania');
INSERT INTO country VALUES ('LU', 'Luxembourg');
INSERT INTO country VALUES ('MO', 'Macau S.A.R.');
INSERT INTO country VALUES ('MK', 'Macedonia, Former Yugoslav Republic of');
INSERT INTO country VALUES ('MG', 'Madagascar');
INSERT INTO country VALUES ('MW', 'Malawi');
INSERT INTO country VALUES ('MY', 'Malaysia');
INSERT INTO country VALUES ('MV', 'Maldives');
INSERT INTO country VALUES ('ML', 'Mali');
INSERT INTO country VALUES ('MT', 'Malta');
INSERT INTO country VALUES ('MH', 'Marshall Islands');
INSERT INTO country VALUES ('MQ', 'Martinique');
INSERT INTO country VALUES ('MR', 'Mauritania');
INSERT INTO country VALUES ('MU', 'Mauritius');
INSERT INTO country VALUES ('YT', 'Mayotte');
INSERT INTO country VALUES ('MX', 'Mexico');
INSERT INTO country VALUES ('FM', 'Micronesia');
INSERT INTO country VALUES ('MD', 'Moldova');
INSERT INTO country VALUES ('MC', 'Monaco');
INSERT INTO country VALUES ('MN', 'Mongolia');
INSERT INTO country VALUES ('MS', 'Montserrat');
INSERT INTO country VALUES ('MA', 'Morocco');
INSERT INTO country VALUES ('MZ', 'Mozambique');
INSERT INTO country VALUES ('MM', 'Myanmar');
INSERT INTO country VALUES ('NA', 'Namibia');
INSERT INTO country VALUES ('NR', 'Nauru');
INSERT INTO country VALUES ('NP', 'Nepal');
INSERT INTO country VALUES ('AN', 'Netherlands Antilles');
INSERT INTO country VALUES ('NL', 'Netherlands, The');
INSERT INTO country VALUES ('NC', 'New Caledonia');
INSERT INTO country VALUES ('NZ', 'New Zealand');
INSERT INTO country VALUES ('NI', 'Nicaragua');
INSERT INTO country VALUES ('NE', 'Niger');
INSERT INTO country VALUES ('NG', 'Nigeria');
INSERT INTO country VALUES ('NU', 'Niue');
INSERT INTO country VALUES ('NF', 'Norfolk Island');
INSERT INTO country VALUES ('MP', 'Northern Mariana Islands');
INSERT INTO country VALUES ('NO', 'Norway');
INSERT INTO country VALUES ('OM', 'Oman');
INSERT INTO country VALUES ('PK', 'Pakistan');
INSERT INTO country VALUES ('PW', 'Palau');
INSERT INTO country VALUES ('PA', 'Panama');
INSERT INTO country VALUES ('PG', 'Papua new Guinea');
INSERT INTO country VALUES ('PY', 'Paraguay');
INSERT INTO country VALUES ('PE', 'Peru');
INSERT INTO country VALUES ('PH', 'Philippines');
INSERT INTO country VALUES ('PN', 'Pitcairn Island');
INSERT INTO country VALUES ('PL', 'Poland');
INSERT INTO country VALUES ('PT', 'Portugal');
INSERT INTO country VALUES ('PR', 'Puerto Rico');
INSERT INTO country VALUES ('QA', 'Qatar');
INSERT INTO country VALUES ('RE', 'Reunion');
INSERT INTO country VALUES ('RO', 'Romania');
INSERT INTO country VALUES ('RU', 'Russia');
INSERT INTO country VALUES ('RW', 'Rwanda');
INSERT INTO country VALUES ('SH', 'Saint Helena');
INSERT INTO country VALUES ('KN', 'Saint Kitts And Nevis');
INSERT INTO country VALUES ('LC', 'Saint Lucia');
INSERT INTO country VALUES ('PM', 'Saint Pierre and Miquelon');
INSERT INTO country VALUES ('VC', 'Saint Vincent And The Grenadines');
INSERT INTO country VALUES ('WS', 'Samoa');
INSERT INTO country VALUES ('SM', 'San Marino');
INSERT INTO country VALUES ('ST', 'Sao Tome and Principe');
INSERT INTO country VALUES ('SA', 'Saudi Arabia');
INSERT INTO country VALUES ('SN', 'Senegal');
INSERT INTO country VALUES ('SC', 'Seychelles');
INSERT INTO country VALUES ('SL', 'Sierra Leone');
INSERT INTO country VALUES ('SG', 'Singapore');
INSERT INTO country VALUES ('SK', 'Slovakia');
INSERT INTO country VALUES ('SI', 'Slovenia');
INSERT INTO country VALUES ('SB', 'Solomon Islands');
INSERT INTO country VALUES ('SO', 'Somalia');
INSERT INTO country VALUES ('ZA', 'South Africa');
INSERT INTO country VALUES ('GS', 'South Georgia And The South Sandwich Islands');
INSERT INTO country VALUES ('ES', 'Spain');
INSERT INTO country VALUES ('LK', 'Sri Lanka');
INSERT INTO country VALUES ('SD', 'Sudan');
INSERT INTO country VALUES ('SR', 'Suriname');
INSERT INTO country VALUES ('SJ', 'Svalbard And Jan Mayen Islands');
INSERT INTO country VALUES ('SZ', 'Swaziland');
INSERT INTO country VALUES ('SE', 'Sweden');
INSERT INTO country VALUES ('CH', 'Switzerland');
INSERT INTO country VALUES ('SY', 'Syria');
INSERT INTO country VALUES ('TW', 'Taiwan');
INSERT INTO country VALUES ('TJ', 'Tajikistan');
INSERT INTO country VALUES ('TZ', 'Tanzania');
INSERT INTO country VALUES ('TH', 'Thailand');
INSERT INTO country VALUES ('TG', 'Togo');
INSERT INTO country VALUES ('TK', 'Tokelau');
INSERT INTO country VALUES ('TO', 'Tonga');
INSERT INTO country VALUES ('TT', 'Trinidad And Tobago');
INSERT INTO country VALUES ('TN', 'Tunisia');
INSERT INTO country VALUES ('TR', 'Turkey');
INSERT INTO country VALUES ('TM', 'Turkmenistan');
INSERT INTO country VALUES ('TC', 'Turks And Caicos Islands');
INSERT INTO country VALUES ('TV', 'Tuvalu');
INSERT INTO country VALUES ('UG', 'Uganda');
INSERT INTO country VALUES ('UA', 'Ukraine');
INSERT INTO country VALUES ('AE', 'United Arab Emirates');
INSERT INTO country VALUES ('UK', 'United Kingdom');
INSERT INTO country VALUES ('US', 'United States');
INSERT INTO country VALUES ('UM', 'United States Minor Outlying Islands');
INSERT INTO country VALUES ('UY', 'Uruguay');
INSERT INTO country VALUES ('UZ', 'Uzbekistan');
INSERT INTO country VALUES ('VU', 'Vanuatu');
INSERT INTO country VALUES ('VA', 'Vatican City State (Holy See)');
INSERT INTO country VALUES ('VE', 'Venezuela');
INSERT INTO country VALUES ('VN', 'Vietnam');
INSERT INTO country VALUES ('VG', 'Virgin Islands (British)');
INSERT INTO country VALUES ('VI', 'Virgin Islands (US)');
INSERT INTO country VALUES ('WF', 'Wallis And Futuna Islands');
INSERT INTO country VALUES ('YE', 'Yemen');
INSERT INTO country VALUES ('YU', 'Yugoslavia');
INSERT INTO country VALUES ('ZM', 'Zambia');
INSERT INTO country VALUES ('ZW', 'Zimbabwe');


INSERT INTO currency VALUES (1, 'Argentine Peso', 'ARS', 2.96, 1, 0);
INSERT INTO currency VALUES (2, 'Australian Dollar', 'AUD', 1.46, 1, 0);
INSERT INTO currency VALUES (3, 'Brazilian Real', 'BRL', 3.23, 1, 0);
INSERT INTO currency VALUES (4, 'British Pound', 'GBP', 0.58, 1, 0);
INSERT INTO currency VALUES (5, 'Euro Dollar', 'EUR', 0.85, 1, 0);
INSERT INTO currency VALUES (6, 'Hong Kong Dollar', 'HKD', 7.88, 1, 0);
INSERT INTO currency VALUES (7, 'Indian Rupee', 'INR', 45.85, 1, 0);
INSERT INTO currency VALUES (8, 'Japanese Yen', 'JPY', 113.77, 1, 0);
INSERT INTO currency VALUES (9, 'Korean Won', 'KRW', 1188.77, 1, 0);
INSERT INTO currency VALUES (10, 'Malaysian Ringgit', 'MYR', 3.85, 1, 0);
INSERT INTO currency VALUES (11, 'New Zealand Dollar', 'NZD', 1.65, 1, 0);
INSERT INTO currency VALUES (12, 'Philippine Peso', 'PHP', 56.54, 1, 0);
INSERT INTO currency VALUES (13, 'Russian Rouble', 'RUB', 29.31, 1, 0);
INSERT INTO currency VALUES (14, 'Saudi Arabian Riyal', 'SAR', 3.81, 1, 0);
INSERT INTO currency VALUES (15, 'Singapore Dollar', 'SGD', 1.73, 1, 0);
INSERT INTO currency VALUES (16, 'Swiss Franc', 'CHF', 1.31, 1, 0);
INSERT INTO currency VALUES (17, 'Taiwan Dollar', 'TWD', 33.96, 1, 0);
INSERT INTO currency VALUES (18, 'Thai Bhat', 'THB', 41.19, 1, 0);
INSERT INTO currency VALUES (19, 'US Dollar', 'USD', 1.00, 1, 1);


INSERT INTO email_admin VALUES (1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);


INSERT INTO email_settings VALUES (1, 'local', '', '', 25, 1, '', '', 'HTML');


INSERT INTO email_template VALUES (1, '[Admin Name]', '[Admin Email]', '[User Name] has been added to Socket Timesheet', 'Hi [User Name],\r\n\r\nYou have been successfully added to the Socket Timesheet system.\r\n\r\nLogin: [Login]\r\nPassword: [Password]\r\n\r\n\r\nregards,\r\n[Admin Name]', 'admin_user_added', 'Add New User Notification');
INSERT INTO email_template VALUES (2, '[Admin Name]', '[Admin Email]', 'Your User Record Has Been Updated By Administrator', 'Hi [User Name],\n\nYour user record has been updated by the Administrator.\n\n\nregards,\n[Admin Name]', 'admin_user_updated', 'User Record Update Notification');
INSERT INTO email_template VALUES (3, '[Admin Name]', '[Admin Email]', 'Your account has been deleted by Administrator', 'Hi [User Name],\r\n\r\nYour account in Socket Timesheet has been deleted by the Administrator.\r\n\r\n\r\nregards,\r\n[Admin Name]', 'admin_user_deleted', 'User Deleted Notification');
INSERT INTO email_template VALUES (4, '[Admin Name]', '[Admin Email]', 'Your account has been disabled', 'Hi [User Name],\n\nYour account has been disabled by the Administrator.\n\n\nregards,\n[Admin Name]', 'admin_user_disabled', 'User Account Disabled Notification');
INSERT INTO email_template VALUES (5, '[Admin Name]', '[Admin Email]', 'Your password has been changed', 'Hi [User Name],\r\n\r\nYour password has been changed by the Administrator.\r\n\r\n\r\nregards,\r\n[Admin Name]', 'admin_password_changed', 'User Password Changed Notification');
INSERT INTO email_template VALUES (6, '[PM Name]', '[PM Email]', 'Project: [Project Name] Added', 'Hi,\r\n\r\nProject [Project Name] has been added.\r\n\r\nProject Manager \r\n[PM Name]\r\n\r\nTeam Members\r\n[Team Name]\r\n\r\nStart Date\r\n[Start Date]\r\n\r\nEnd Date\r\n[End Date]\r\n\r\n\r\nregards,\r\n[PM Name]', 'project_added', 'New Project Added Notification');
INSERT INTO email_template VALUES (7, '[PM Name]', '[PM Email]', 'Project: [Project Name] Updated', 'Hi,\r\n\r\nProject [Project Name] has been updated by Project Manager.\r\n\r\nProject Manager \r\n[PM Name]\r\n\r\nTeam Members\r\n[Team Name]\r\n\r\n\r\nregards,\r\n[PM Name]', 'project_updated', 'Project Updated Notification');
INSERT INTO email_template VALUES (8, '[PM Name]', '[PM Email]', 'Project: [Project Name] Deleted', 'Hi,\n\nProject [Project Name] has been deleted by Project Manager.\n\nProject Manager \n[PM Name]\n\nTeam Members\n[Team Name]\n\n\nregards,\n[PM Name]', 'project_deleted', 'Project Deleted Notification');
INSERT INTO email_template VALUES (9, '[PM Name]', '[PM Email]', 'Project: [Project Name] Is Now Starting', 'Hi,\r\n\r\nProject [Project Name] is now starting.\r\n\r\nProject Manager \r\n[PM Name]\r\n\r\nTeam Members\r\n[Team Name]\r\n\r\nStart Date [Start Date]\r\n\r\n\r\nregards,\r\n[PM Name]', 'project_started', 'Project Started Notification');
INSERT INTO email_template VALUES (10, '[PM Name]', '[PM Email]', 'Project: [Project Name] Has Reached The End Date', 'Hi,\n\nProject [Project Name] has reached the end date.\n\nProject Manager \n[PM Name]\n\nTeam Members\n[Team Name]\n\nEnd Date: [End Date]\n\n\nregards,\n[PM Name]', 'project_ended', 'Project End Date Notification');
INSERT INTO email_template VALUES (11, 'Timesheet Email Notification', '[User Email]', 'Timesheet Submitted', 'Hi,\r\n\r\nTimesheet for week [Week] has been submitted by [User Name].\r\n\r\nTasks\r\n[Timesheet Tasks]\r\n\r\nTimeoff\r\n[Timeoff Tasks]\r\n\r\nOverall\r\n[Overall Status]\r\n\r\n\r\nregards,\r\nTimesheet Email Notification', 'timesheet_approval', 'Timesheet Submitted Notification');
INSERT INTO email_template VALUES (12, 'Timesheet Email Notification', '[Admin Email]', 'Timesheet Approved', 'Hi [User Name],\r\n\r\nYour timesheet submission for the week of [Week] has been approved. Current status below:\r\n\r\nTasks\r\n[Timesheet Tasks]\r\n\r\nTimeoff\r\n[Timeoff Tasks]\r\n\r\nOverall\r\n[Overall Status]\r\n\r\n\r\nregards,\r\nTimesheet Email Notification', 'timesheet_approved', 'Timesheet Approved Notification');
INSERT INTO email_template VALUES (13, 'Timesheet Email Notification', '[Admin Email]', 'Timesheet Rejected', 'Hi [User Name],\r\n\r\nYour timesheet submission for the week of [Week] has been rejected. Current status below:\r\n\r\nTasks\r\n[Timesheet Tasks]\r\n\r\nTimeoff\r\n[Timeoff Tasks]\r\n\r\nOverall\r\n[Overall Status]\r\n\r\n\r\nregards,\r\nTimesheet Email Notification', 'timesheet_rejected', 'Timesheet Rejection Notification');
INSERT INTO email_template VALUES (14, 'Timesheet Email Notification', '[User Email]', 'Timesheet Undo Request', 'Hi,\n\nUser [User Name] has submitted a Timesheet Undo Request for the week of [Week]. Kindly take appropriate action.\n\n\nregards,\nTimesheet Email Notification', 'timesheet_undo_request', 'Timesheet Undo Request Notification');
INSERT INTO email_template VALUES (15, 'Timesheet Email Notification', '[User Email]', 'Timesheet Undo Request Cancellation', 'Hi,\n\nFYI, User [User Name] has cancelled Undo Request for the week of [Week].\n\n\nregards,\nTimesheet Email Notification', 'timesheet_undo_cancel', 'Timesheet Undo Request Cancellation Notification');
INSERT INTO email_template VALUES (16, '[Admin Name]', '[Admin Email]', 'Timesheet Undo by Administrator', 'Hi [User Name],\r\n\r\nYour Timesheet for the week of [Week] has been Undo by the Administrator.\r\n\r\n\r\nregards,\r\n[Admin Name]', 'timesheet_undo_approved', 'Timesheet Undo Approved Notification');
INSERT INTO email_template VALUES (17, 'Timesheet Email Notification', '[Admin Email]', 'Your Timesheet Is Due', 'Hi [User Name],\r\n\r\nYour timesheet for the week of [Week] is now due for submission. Please take appropriate action.\r\n\r\n\r\nregards,\r\nTimesheet Email Notification', 'timesheet_due', 'Timesheet Due Notification');
INSERT INTO email_template VALUES (18, 'Timesheet Email Notification', '[Admin Email]', 'Your Timesheet Is Overdue', 'Hi [User Name],\n\nYour timesheet for the week of [Week] is now overdue. Please take appropriate action ASAP.\n\n\nregards,\nTimesheet Email Notification', 'timesheet_overdue', 'Timesheet Overdue Notification');
INSERT INTO email_template VALUES (19, 'Expenses Email Notification', '[Admin Email]', 'Expenses Submitted By [User Name]', 'Hi,\n\nExpenses submitted by [User Name]\n\nDescription\n[Expenses Description]\n\nOverall Status\n[Overall Status]\n\n\nregards.\nExpenses Email Notification', 'expenses_approval', 'Expenses Submitted Notification');
INSERT INTO email_template VALUES (20, 'Expenses Email Notification', '[Admin Email]', 'Expenses Approved', 'Hi,\n\nYour expenses submission has been approved. Current status below:\n\nDescription\n[Expenses Description]\n\nOverall\n[Overall Status]\n\n\nregards,\nExpenses Email Notification', 'expenses_approved', 'Expenses Approval Notification');
INSERT INTO email_template VALUES (21, 'Expenses Email Notification', '[Admin Email]', 'Expenses Rejected', 'Hi,\n\nYour expenses submission has been rejected. Current status below:\n\nDescription\n[Expenses Description]\n\nOverall\n[Overall Status]\n\n\nregards,\nExpenses Email Notification', 'expenses_rejected', 'Expenses Rejection Notification');
INSERT INTO email_template VALUES (22, '[User Name]', '[Admin Email]', 'Expenses Undo Request', 'Hi,\n\nUser [User Name] has submitted a Expenses Undo Request for Expense: [Expenses Description]. Kindly take appropriate action.\n\n\nregards,\nExpenses Email Notification', 'expenses_undo_request', 'Expenses Undo Request Notification');
INSERT INTO email_template VALUES (23, '[User Name]', '[User Email]', 'Expenses Undo Request Cancellation', 'Hi,\n\nUser [User Name] has cancelled the Undo Request for Expenses [Expenses Description]. Kindly take note.\n\n\nregards,\nExpenses Email Notification', 'expenses_undo_cancel', 'Expenses Undo Request Cancellation Notification');
INSERT INTO email_template VALUES (24, '[Admin Name]', '[Admin Email]', 'Expenses Undo Request Approved', 'Hi [User Name],\n\nYour Expenses Undo Request for [Expenses Description] has been approved.\n\n\nregards,\n[Admin Name]', 'expenses_undo_approved', 'Expenses Undo Approved Notification');
INSERT INTO email_template VALUES (25, '[Admin Name]', '[Admin Email]', 'Timesheet Overdue [Week]', 'Hi [User Name],\r\n\r\nYour current timesheet for the week of [Week] is now overdue. Please take appropriate action ASAP.\r\n\r\n\r\nbest regards,\r\n[Admin Name]', 'timesheet_overdue_manual', 'Timesheet Overdue Notification');


INSERT INTO employee_type VALUES (1, 'Full-time salaried', 'Full Time Employee');
INSERT INTO employee_type VALUES (2, 'Part-time Salaried', 'Part Time Employee');
INSERT INTO employee_type VALUES (3, 'Full-time hourly', 'Full Time On Hourly Basis');
INSERT INTO employee_type VALUES (4, 'Part-time Hourly', 'Part Time On Hourly Basis');
INSERT INTO employee_type VALUES (5, 'Contractor', '');
INSERT INTO employee_type VALUES (6, 'Consultant', '');
INSERT INTO employee_type VALUES (7, 'Administrator', '');
INSERT INTO employee_type VALUES (9, 'Project Manager', 'PM for specific project');


INSERT INTO expense VALUES (1, 'Airfare', 'AF9098', 'Air flights and related', 1);
INSERT INTO expense VALUES (2, 'Car Rental', 'CR5678', 'This is for car rental', 1);
INSERT INTO expense VALUES (3, 'Entertainment', 'ET7890', 'Where is the description?', 1);
INSERT INTO expense VALUES (4, 'Hotel', 'HT898', 'This is another one', 1);
INSERT INTO expense VALUES (5, 'Local Transporation', 'LT6754', '', 1);
INSERT INTO expense VALUES (6, 'Meals', 'ME789', '', 1);
INSERT INTO expense VALUES (7, 'Miscellaneous', 'MS912', '', 1);
INSERT INTO expense VALUES (8, 'Parking', 'PK9123', '', 1);
INSERT INTO expense VALUES (9, 'Telephone', 'T1000', '', 1);
INSERT INTO expense VALUES (10, 'Mileage', 'ML8780', '', 1);
INSERT INTO expense VALUES (11, 'Tips', 'TI9098', 'Tips for hotel restaurant etc', 1);
INSERT INTO expense VALUES (12, 'Laundry', 'LAU8909', 'Laundry Expenses Etc', 0);


INSERT INTO name_format VALUES (1, 'CONCAT_WS(", ",LName,FName)', 'LName, FName');
INSERT INTO name_format VALUES (2, 'CONCAT_WS(", ",FName,LName)', 'FName, LName');
INSERT INTO name_format VALUES (3, 'FName', 'FName');
INSERT INTO name_format VALUES (4, 'LName', 'LName');


INSERT INTO period VALUES (1, 0, '2005-12-18', 1, 0, 0, '09:00:00', '17:00:00', 40.00, 8.00, 5, 0, '0:6:', 0, 1, 0, 0);


INSERT INTO permission VALUES (4, 'Administrator', 'administrator', 'Full Access', 1);
INSERT INTO permission VALUES (3, 'Supervisor', 'supervisor', 'View subordinate timesheet, approve or reject timesheet and report', 1);
INSERT INTO permission VALUES (2, 'Project Manager', 'pm', 'Setup and manage projects, approve timesheets and generate reports', 1);
INSERT INTO permission VALUES (1, 'Timesheet', 'timesheet', 'General permission with the ability to enter time on a timesheet', 1);
INSERT INTO permission VALUES (5, 'All Reports', 'report', 'Can use reporting functions with permissions', 1);
INSERT INTO permission VALUES (6, 'Expenses', 'expenses', 'Submit Expenses', 1);


INSERT INTO phase VALUES (1, 'Requirement', 1);
INSERT INTO phase VALUES (2, 'Design', 1);
INSERT INTO phase VALUES (3, 'Implementation', 1);
INSERT INTO phase VALUES (4, 'Integration', 1);
INSERT INTO phase VALUES (5, 'Validation', 1);
INSERT INTO phase VALUES (6, 'Installation', 1);
INSERT INTO phase VALUES (7, 'Maintenance', 1);


INSERT INTO project_config VALUES (1, 1, 1, 1, 'PRJ', 5, '', 'TASK', 5, '','Name','ASC');


INSERT INTO template VALUES (1, 'Classic-En', 'skins', 'classic', 'en');


INSERT INTO time_off VALUES (1, 'Administrative Tasks', 'ADM9099', 'Enable Again?', 1);
INSERT INTO time_off VALUES (3, 'IT Support', 'IT5676', '', 1);
INSERT INTO time_off VALUES (4, 'Leave - Annual', 'LA0909', '', 1);
INSERT INTO time_off VALUES (5, 'Leave - Emergency', 'LE9876', '', 1);
INSERT INTO time_off VALUES (6, 'Leave - Medical', 'LM9890', '', 1);
INSERT INTO time_off VALUES (7, 'Leave - Other Approved Leave', 'LO765', '', 1);
INSERT INTO time_off VALUES (8, 'Leave - Unpaid', 'LU0987', '', 1);
INSERT INTO time_off VALUES (9, 'Public Holiday', 'PH12432', '', 1);
INSERT INTO time_off VALUES (10, 'Business Pursuit', 'BP9098', 'General Business Pursuit''s', 1);
INSERT INTO time_off VALUES (11, 'Training - External', 'TE9000', '', 1);
INSERT INTO time_off VALUES (12, 'Research', 'RS0900', 'Research From Various Sources', 1);
INSERT INTO time_off VALUES (13, 'Leisure Time', 'LT0909', 'This is my description', 1);
INSERT INTO time_off VALUES (14, 'Lost Time (Blackout etc)', 'ND911', 'Recognized natural disaster (company)', 1);


INSERT INTO timesheet_approval VALUES (1, 0, 'Task', 'Project Manager', 0);
INSERT INTO timesheet_approval VALUES (2, 0, 'Timeoff', 'Supervisor', 0);
INSERT INTO timesheet_approval VALUES (3, 0, 'Timeoff', 'Secondary Supervisor', 0);
INSERT INTO timesheet_approval VALUES (4, 0, 'Task', 'Secondary Project Manager', 0);
INSERT INTO timesheet_approval VALUES (5, 0, 'Overall', 'System', 0);

INSERT INTO calendar_category VALUES (1,'General',1);
INSERT INTO calendar_category VALUES (2,'Event',1);
INSERT INTO calendar_category VALUES (3,'Public Holiday',1);