/* 
	the format of the tree definition file is simple,
	you can find specification in the Tigra Menu documentation at:
	
	http://www.softcomplex.com/products/tigra_tree_menu/docs/index.html#hierarchy
*/

var TREE_ITEMS = [
	['Window', 0, 
		['Description'],
		['Properties', 0,
			['client'],
			['closed'],
			['defaultStatus'],
			['dialogArguments'],
			['dialogHeight'],
			['dialogWidth'],
			['dialogTop'],
			['dialogLeft'],
			['document', 0, 
				['Description'],
				['Properties', 0, 
					['activeElement'],
					['aLinkColor'],
					['bgColor'],
					['cookie'],
					['domain'],
					['fgColor'],
					['lastModified'],
					['linkColor'],
					['location'],
					['parentWindow'],
					['referrer'],
					['readyState'],
					['title'],
					['URL'],
					['vlinkColor']
				],
				['Methods', 0, 
					['close'],
					['createElement'],
					['execCommand'],
					['elementFromPoint'],
					['open'],
					['queryCommandEnabled'],
					['queryCommandIndeterm'],
					['queryCommandState'],
					['queryCommandSupported'],
					['queryCommandValue'],
					['write'],
					['writeln']
				],
				['Collections', 0, 
					['all'],
					['anchors'],
					['applets'],
					['forms'],
					['frames'],
					['embeds'],
					['images'],
					['links'],
					['scripts'],
					['styleSheets']
				],
				['Example']
			],
			['event'],
			['history', 0, 
				['Description'],
				['Properties', 0, 
					['length']
				],
				['Methods', 0,
					['back'],
					['forward'],
					['go']
				],
				['Example']
			],
			['length'],
			['location'],
			['name'],
			['navigator'],
			['offscreenBuffering'],
			['opener'],
			['parent'],
			['returnValue'],
			['self'],
			['status'],
			['top']
		],
		['Methods', 0, 
			['alert'],
			['blur'],
			['clearInterval'],
			['clearTimeout'],
			['close'],
			['confirm'],
			['execScript'],
			['focus '],
			['navigate'],
			['open'],
			['prompt'],
			['scroll'],
			['setInterval'],
			['setTimeout'],
			['showHelp'],
			['showModalDialog']
		],
		['Collections', 0,
			['frames']
		],
		['Example']
	]
];